substitutions:
  devicename: "watering"
  friendly_name: "浇花器"
  # 引脚定义
  pin_relay: GPIO02      # 水阀继电器
  pin_soil: GPIO00       # 土壤检测 (ADC)
  pin_i2c_sda: GPIO18    # 温湿度计
  pin_i2c_scl: GPIO19    # 温湿度计
  

esphome:
  name: ${devicename}
  friendly_name: "浇花器"

esp32:
  #variant: esp32c3
  board: esp32-c3-devkitc-02
  flash_size: 4MB
  cpu_frequency: 160MHZ
  framework:
    type: esp-idf
    
ota:
  - platform: esphome
    password: !secret ota_password
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${devicename}-fallback"
    password: "123456789"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_key


# ------------------------------------------------
# 传感器 (仅显示数据)
# ------------------------------------------------
i2c:
  sda: ${pin_i2c_sda}
  scl: ${pin_i2c_scl}
  scan: true
  id: bus_a
  
sensor:
  # 电容式土壤湿度传感器
  # 初始状态：输出电压值 (V)。方便先观察读数。
  # 等确定了干湿数值后，取消下方unit_of_measurement和filters的注释即可变成百分比。
  - platform: adc
    pin: ${pin_soil}
    name: "Soil Moisture"
    id: soil_sensor
    update_interval: 5s
    attenuation: 11db
   
   # --- 校准区域 (使用前请取消注释并填入你的数值) ---
   # unit_of_measurement: "%"
   # filters:
   #   - sliding_window_moving_average:
   #       window_size: 10
   #       send_every: 5
   #   - calibrate_linear:
   #       # 格式: 读到的电压 -> 显示的百分比
   #       - 2.10 -> 0.0   # 空气中 (干)
   #       - 0.70 -> 100.0 # 水中 (湿)
   #   - lambda: |
   #       if (x < 0) return 0;
   #       if (x > 100) return 100;
   #       return x;
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    
  # 空气温湿度传感器
  - platform: aht10
    variant: AHT20
    temperature:
      name: "Air Temperature"
    humidity:
      name: "Air Humidity"
    update_interval: 60s

# ------------------------------------------------
# 手动控制配置
# ------------------------------------------------
script:
  # 自动关闭水阀用脚本
  - id: water_timer_script
    mode: restart  # 如果再次调用时已经在运行，会重置时间并重新开始
    then:
      - logger.log: "开始浇水"
      - delay: !lambda 'return id(manual_duration).state * 1000;'
      - logger.log: "浇水结束自动关闭水泵"
      - switch.turn_off: relay_switch

# 用于设置“手动浇水持续几秒”的配置项
number:
  - platform: template
    name: "Watering Duration"
    id: manual_duration
    optimistic: true
    min_value: 1
    max_value: 90
    step: 1
    initial_value: 30
    unit_of_measurement: "s"
    mode: box

# 水阀开关
switch:
  - platform: gpio
    pin: ${pin_relay}
    name: "Start Watering"
    id: relay_switch
    icon: "mdi:water-pump"
    restore_mode: ALWAYS_OFF
    
    on_turn_on:
       - script.execute: water_timer_script
    # 防止脚本还在倒计时
    on_turn_off:
       - script.stop: water_timer_script


# ------------------------------------------------
# 水泵安全保底
# ------------------------------------------------

interval:
  - interval: 1s
    then:
      - lambda: |-
          // 静态变量，用来记录水泵连续运行了多少秒
          static int run_seconds = 0;
          
          if (id(relay_switch).state) {
            run_seconds++;
            ESP_LOGD("main", "水泵已运行: %d 秒", run_seconds);
            
            // 如果超过 60 秒
            if (run_seconds > 60) {
              ESP_LOGE("main", "水泵开启超时，强制关闭！");
              id(relay_switch).turn_off();
              run_seconds = 0;
            }
          } else {
            // 如果水泵是关的，重置计数器
            run_seconds = 0;
          }